sudo: required
services:
  - docker

before_install:
  - docker build -t ejemaster/docker-react -f Dockerfile.dev .

script:
  - docker run ejemaster/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-1.0"
  env: "DockerReact10-env"
  bucket_name: "elasticbeanstalk-eu-central-1-968812419730"
  bucket_path: "docker-react-1.0"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

